services:
  db:
    image: postgres:16.4
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/data/:/var/lib/postgresql/data/

volumes:
  postgres_data:

  #  docker-compose up -d --build --force-recreate
  #  docker-compose exec db bash
  #  docker-compose down
  #  docker-compose ps